services:
  pipeline:
    build:
      context: .
    volumes:
      - ".:/opt/code"
    container_name: pipeline_service
    healthcheck:
      test: ["CMD", "python", "-c", "print('health check')"]
      interval: 30s
      timeout: 10s
      retries: 3

  bash:
    entrypoint: /bin/bash
    build:
      context: .
    volumes:
      - ".:/opt/code"
    container_name: bash_service
